#!/bin/bash

BASE_PATH=$(realpath ${PWD})/../..
CONFIGURATION_FILE_PATH=${BASE_PATH}/arch/arm/configs/Pipo_M9_Pro_DDR_OC_defconfig
DESTINATION_CONFIGURATION_FILE_PATH=${BASE_PATH}/.config

COMMAND="cp -f ${CONFIGURATION_FILE_PATH} ${DESTINATION_CONFIGURATION_FILE_PATH}"
echo "> $COMMAND"
eval $COMMAND
